/********************************************************************************
** Form generated from reading UI file 'syszuxpinyin.ui'
**
** Created by: Qt User Interface Compiler version 4.8.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SYSZUXPINYIN_H
#define UI_SYSZUXPINYIN_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QHeaderView>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_IMEall
{
public:
    QPushButton *pushButton_u;
    QPushButton *pushButton_t;
    QPushButton *pushButton_y;
    QPushButton *pushButton_i;
    QPushButton *pushButton_q;
    QPushButton *pushButton_zuokuo;
    QPushButton *pushButton_p;
    QPushButton *pushButton_r;
    QPushButton *pushButton_youkuo;
    QPushButton *pushButton_w;
    QPushButton *pushButton_o;
    QPushButton *pushButton_e;
    QPushButton *pushButton_j;
    QPushButton *pushButton_g;
    QPushButton *pushButton_h;
    QPushButton *pushButton_k;
    QPushButton *pushButton_a;
    QPushButton *pushButton_quote;
    QPushButton *pushButton_semicolon;
    QPushButton *pushButton_f;
    QPushButton *pushButton_enter;
    QPushButton *pushButton_s;
    QPushButton *pushButton_l;
    QPushButton *pushButton_d;
    QPushButton *pushButton_m;
    QPushButton *pushButton_b;
    QPushButton *pushButton_n;
    QPushButton *pushButton_comma;
    QPushButton *pushButton_z;
    QPushButton *pushButton_splash;
    QPushButton *pushButton_v;
    QPushButton *pushButton_x;
    QPushButton *pushButton_period;
    QPushButton *pushButton_c;
    QPushButton *pushButton_shift;
    QPushButton *pushButton_whitespace;
    QPushButton *pushButton_up;
    QPushButton *pushButton_backsplash;
    QPushButton *pushButton_left;
    QPushButton *pushButton_right;
    QPushButton *pushButton_down;
    QPushButton *pushButton_n2;
    QPushButton *pushButton_is_hanzi;
    QPushButton *pushButton_ok;
    QPushButton *pushButton_hanzi_7;
    QPushButton *pushButton_hanzi_5;
    QPushButton *pushButton_hanzi_6;
    QPushButton *pushButton_hanzi_8;
    QPushButton *pushButton_hanzi_4;
    QPushButton *pushButton_hanzi_2;
    QPushButton *pushButton_hanzi_3;
    QPushButton *pushButton_hanzi_left;
    QPushButton *pushButton_hanzi_right;
    QPushButton *pushButton_hanzi_1;
    QLineEdit *lineEdit_pinyin;
    QPushButton *pushButton_n3;
    QPushButton *pushButton_backspace;
    QPushButton *pushButton_n0;
    QPushButton *pushButton_n1;
    QPushButton *pushButton_n6;
    QPushButton *pushButton_deng;
    QPushButton *pushButton_gang;
    QPushButton *pushButton_n5;
    QPushButton *pushButton_n7;
    QPushButton *pushButton_n8;
    QPushButton *pushButton_n4;
    QPushButton *pushButton_n9;

    void setupUi(QDialog *IMEall)
    {
        if (IMEall->objectName().isEmpty())
            IMEall->setObjectName(QString::fromUtf8("IMEall"));
        IMEall->resize(600, 351);
        pushButton_u = new QPushButton(IMEall);
        pushButton_u->setObjectName(QString::fromUtf8("pushButton_u"));
        pushButton_u->setGeometry(QRect(342, 140, 45, 45));
        QFont font;
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        pushButton_u->setFont(font);
        pushButton_t = new QPushButton(IMEall);
        pushButton_t->setObjectName(QString::fromUtf8("pushButton_t"));
        pushButton_t->setGeometry(QRect(241, 140, 45, 45));
        pushButton_t->setFont(font);
        pushButton_y = new QPushButton(IMEall);
        pushButton_y->setObjectName(QString::fromUtf8("pushButton_y"));
        pushButton_y->setGeometry(QRect(291, 140, 45, 45));
        pushButton_y->setFont(font);
        pushButton_i = new QPushButton(IMEall);
        pushButton_i->setObjectName(QString::fromUtf8("pushButton_i"));
        pushButton_i->setGeometry(QRect(392, 140, 45, 45));
        pushButton_i->setFont(font);
        pushButton_q = new QPushButton(IMEall);
        pushButton_q->setObjectName(QString::fromUtf8("pushButton_q"));
        pushButton_q->setGeometry(QRect(39, 140, 45, 45));
        pushButton_q->setFont(font);
        pushButton_zuokuo = new QPushButton(IMEall);
        pushButton_zuokuo->setObjectName(QString::fromUtf8("pushButton_zuokuo"));
        pushButton_zuokuo->setGeometry(QRect(0, 190, 45, 45));
        pushButton_zuokuo->setFont(font);
        pushButton_p = new QPushButton(IMEall);
        pushButton_p->setObjectName(QString::fromUtf8("pushButton_p"));
        pushButton_p->setGeometry(QRect(493, 140, 45, 45));
        pushButton_p->setFont(font);
        pushButton_r = new QPushButton(IMEall);
        pushButton_r->setObjectName(QString::fromUtf8("pushButton_r"));
        pushButton_r->setGeometry(QRect(191, 140, 45, 45));
        pushButton_r->setFont(font);
        pushButton_youkuo = new QPushButton(IMEall);
        pushButton_youkuo->setObjectName(QString::fromUtf8("pushButton_youkuo"));
        pushButton_youkuo->setGeometry(QRect(0, 140, 45, 45));
        pushButton_youkuo->setFont(font);
        pushButton_w = new QPushButton(IMEall);
        pushButton_w->setObjectName(QString::fromUtf8("pushButton_w"));
        pushButton_w->setGeometry(QRect(90, 140, 45, 45));
        pushButton_w->setFont(font);
        pushButton_o = new QPushButton(IMEall);
        pushButton_o->setObjectName(QString::fromUtf8("pushButton_o"));
        pushButton_o->setGeometry(QRect(443, 140, 45, 45));
        pushButton_o->setFont(font);
        pushButton_e = new QPushButton(IMEall);
        pushButton_e->setObjectName(QString::fromUtf8("pushButton_e"));
        pushButton_e->setGeometry(QRect(140, 140, 45, 45));
        pushButton_e->setFont(font);
        pushButton_j = new QPushButton(IMEall);
        pushButton_j->setObjectName(QString::fromUtf8("pushButton_j"));
        pushButton_j->setGeometry(QRect(364, 191, 45, 45));
        pushButton_j->setFont(font);
        pushButton_g = new QPushButton(IMEall);
        pushButton_g->setObjectName(QString::fromUtf8("pushButton_g"));
        pushButton_g->setGeometry(QRect(263, 191, 45, 45));
        pushButton_g->setFont(font);
        pushButton_h = new QPushButton(IMEall);
        pushButton_h->setObjectName(QString::fromUtf8("pushButton_h"));
        pushButton_h->setGeometry(QRect(313, 191, 45, 45));
        pushButton_h->setFont(font);
        pushButton_k = new QPushButton(IMEall);
        pushButton_k->setObjectName(QString::fromUtf8("pushButton_k"));
        pushButton_k->setGeometry(QRect(414, 191, 45, 45));
        pushButton_k->setFont(font);
        pushButton_a = new QPushButton(IMEall);
        pushButton_a->setObjectName(QString::fromUtf8("pushButton_a"));
        pushButton_a->setGeometry(QRect(61, 191, 45, 45));
        pushButton_a->setFont(font);
        pushButton_quote = new QPushButton(IMEall);
        pushButton_quote->setObjectName(QString::fromUtf8("pushButton_quote"));
        pushButton_quote->setGeometry(QRect(0, 250, 45, 45));
        pushButton_quote->setFont(font);
        pushButton_semicolon = new QPushButton(IMEall);
        pushButton_semicolon->setObjectName(QString::fromUtf8("pushButton_semicolon"));
        pushButton_semicolon->setGeometry(QRect(0, 300, 45, 45));
        pushButton_semicolon->setFont(font);
        pushButton_f = new QPushButton(IMEall);
        pushButton_f->setObjectName(QString::fromUtf8("pushButton_f"));
        pushButton_f->setGeometry(QRect(213, 191, 45, 45));
        pushButton_f->setFont(font);
        pushButton_enter = new QPushButton(IMEall);
        pushButton_enter->setObjectName(QString::fromUtf8("pushButton_enter"));
        pushButton_enter->setGeometry(QRect(450, 290, 100, 45));
        pushButton_enter->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/ime/icon4ime/cr_s.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QString::fromUtf8(":/ime/icon4ime/cr_s.png"), QSize(), QIcon::Normal, QIcon::On);
        pushButton_enter->setIcon(icon);
        pushButton_enter->setIconSize(QSize(48, 48));
        pushButton_s = new QPushButton(IMEall);
        pushButton_s->setObjectName(QString::fromUtf8("pushButton_s"));
        pushButton_s->setGeometry(QRect(112, 191, 45, 45));
        pushButton_s->setFont(font);
        pushButton_l = new QPushButton(IMEall);
        pushButton_l->setObjectName(QString::fromUtf8("pushButton_l"));
        pushButton_l->setGeometry(QRect(465, 191, 45, 45));
        pushButton_l->setFont(font);
        pushButton_d = new QPushButton(IMEall);
        pushButton_d->setObjectName(QString::fromUtf8("pushButton_d"));
        pushButton_d->setGeometry(QRect(162, 191, 45, 45));
        pushButton_d->setFont(font);
        pushButton_m = new QPushButton(IMEall);
        pushButton_m->setObjectName(QString::fromUtf8("pushButton_m"));
        pushButton_m->setGeometry(QRect(390, 240, 45, 45));
        pushButton_m->setFont(font);
        pushButton_b = new QPushButton(IMEall);
        pushButton_b->setObjectName(QString::fromUtf8("pushButton_b"));
        pushButton_b->setGeometry(QRect(290, 240, 45, 45));
        pushButton_b->setFont(font);
        pushButton_n = new QPushButton(IMEall);
        pushButton_n->setObjectName(QString::fromUtf8("pushButton_n"));
        pushButton_n->setGeometry(QRect(340, 240, 45, 45));
        pushButton_n->setFont(font);
        pushButton_comma = new QPushButton(IMEall);
        pushButton_comma->setObjectName(QString::fromUtf8("pushButton_comma"));
        pushButton_comma->setGeometry(QRect(570, 80, 45, 45));
        pushButton_comma->setFont(font);
        pushButton_z = new QPushButton(IMEall);
        pushButton_z->setObjectName(QString::fromUtf8("pushButton_z"));
        pushButton_z->setGeometry(QRect(90, 240, 45, 45));
        pushButton_z->setFont(font);
        pushButton_splash = new QPushButton(IMEall);
        pushButton_splash->setObjectName(QString::fromUtf8("pushButton_splash"));
        pushButton_splash->setGeometry(QRect(540, 80, 45, 45));
        pushButton_splash->setFont(font);
        pushButton_v = new QPushButton(IMEall);
        pushButton_v->setObjectName(QString::fromUtf8("pushButton_v"));
        pushButton_v->setGeometry(QRect(240, 240, 45, 45));
        pushButton_v->setFont(font);
        pushButton_x = new QPushButton(IMEall);
        pushButton_x->setObjectName(QString::fromUtf8("pushButton_x"));
        pushButton_x->setGeometry(QRect(140, 240, 45, 45));
        pushButton_x->setFont(font);
        pushButton_period = new QPushButton(IMEall);
        pushButton_period->setObjectName(QString::fromUtf8("pushButton_period"));
        pushButton_period->setGeometry(QRect(550, 280, 45, 45));
        pushButton_period->setFont(font);
        pushButton_c = new QPushButton(IMEall);
        pushButton_c->setObjectName(QString::fromUtf8("pushButton_c"));
        pushButton_c->setGeometry(QRect(190, 240, 45, 45));
        pushButton_c->setFont(font);
        pushButton_shift = new QPushButton(IMEall);
        pushButton_shift->setObjectName(QString::fromUtf8("pushButton_shift"));
        pushButton_shift->setGeometry(QRect(40, 240, 41, 45));
        pushButton_shift->setFont(font);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/ime/icon4ime/shift.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon1.addFile(QString::fromUtf8(":/ime/icon4ime/shift.png"), QSize(), QIcon::Normal, QIcon::On);
        pushButton_shift->setIcon(icon1);
        pushButton_shift->setIconSize(QSize(48, 48));
        pushButton_whitespace = new QPushButton(IMEall);
        pushButton_whitespace->setObjectName(QString::fromUtf8("pushButton_whitespace"));
        pushButton_whitespace->setGeometry(QRect(220, 290, 210, 45));
        pushButton_whitespace->setFont(font);
        pushButton_up = new QPushButton(IMEall);
        pushButton_up->setObjectName(QString::fromUtf8("pushButton_up"));
        pushButton_up->setGeometry(QRect(540, 230, 60, 45));
        pushButton_up->setFont(font);
        pushButton_backsplash = new QPushButton(IMEall);
        pushButton_backsplash->setObjectName(QString::fromUtf8("pushButton_backsplash"));
        pushButton_backsplash->setGeometry(QRect(621, 140, 45, 45));
        pushButton_backsplash->setFont(font);
        pushButton_left = new QPushButton(IMEall);
        pushButton_left->setObjectName(QString::fromUtf8("pushButton_left"));
        pushButton_left->setGeometry(QRect(540, 180, 60, 45));
        pushButton_left->setFont(font);
        pushButton_right = new QPushButton(IMEall);
        pushButton_right->setObjectName(QString::fromUtf8("pushButton_right"));
        pushButton_right->setGeometry(QRect(621, 300, 60, 45));
        pushButton_right->setFont(font);
        pushButton_down = new QPushButton(IMEall);
        pushButton_down->setObjectName(QString::fromUtf8("pushButton_down"));
        pushButton_down->setGeometry(QRect(540, 130, 60, 45));
        pushButton_down->setFont(font);
        pushButton_n2 = new QPushButton(IMEall);
        pushButton_n2->setObjectName(QString::fromUtf8("pushButton_n2"));
        pushButton_n2->setGeometry(QRect(90, 90, 45, 45));
        pushButton_n2->setFont(font);
        pushButton_n2->setFocusPolicy(Qt::ClickFocus);
        pushButton_is_hanzi = new QPushButton(IMEall);
        pushButton_is_hanzi->setObjectName(QString::fromUtf8("pushButton_is_hanzi"));
        pushButton_is_hanzi->setGeometry(QRect(160, 290, 45, 45));
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_is_hanzi->setFont(font1);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/ime/icon4ime/imesel.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_is_hanzi->setIcon(icon2);
        pushButton_is_hanzi->setIconSize(QSize(48, 48));
        pushButton_ok = new QPushButton(IMEall);
        pushButton_ok->setObjectName(QString::fromUtf8("pushButton_ok"));
        pushButton_ok->setGeometry(QRect(500, 240, 41, 45));
        QPalette palette;
        QBrush brush(QColor(0, 255, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_ok->setPalette(palette);
        QFont font2;
        font2.setPointSize(36);
        font2.setBold(true);
        font2.setWeight(75);
        pushButton_ok->setFont(font2);
        pushButton_hanzi_7 = new QPushButton(IMEall);
        pushButton_hanzi_7->setObjectName(QString::fromUtf8("pushButton_hanzi_7"));
        pushButton_hanzi_7->setGeometry(QRect(392, 50, 45, 35));
        pushButton_hanzi_7->setFont(font1);
        pushButton_hanzi_5 = new QPushButton(IMEall);
        pushButton_hanzi_5->setObjectName(QString::fromUtf8("pushButton_hanzi_5"));
        pushButton_hanzi_5->setGeometry(QRect(291, 50, 45, 35));
        pushButton_hanzi_5->setFont(font1);
        pushButton_hanzi_6 = new QPushButton(IMEall);
        pushButton_hanzi_6->setObjectName(QString::fromUtf8("pushButton_hanzi_6"));
        pushButton_hanzi_6->setGeometry(QRect(341, 50, 45, 35));
        pushButton_hanzi_6->setFont(font1);
        pushButton_hanzi_8 = new QPushButton(IMEall);
        pushButton_hanzi_8->setObjectName(QString::fromUtf8("pushButton_hanzi_8"));
        pushButton_hanzi_8->setGeometry(QRect(442, 50, 45, 35));
        pushButton_hanzi_8->setFont(font1);
        pushButton_hanzi_4 = new QPushButton(IMEall);
        pushButton_hanzi_4->setObjectName(QString::fromUtf8("pushButton_hanzi_4"));
        pushButton_hanzi_4->setGeometry(QRect(241, 50, 45, 35));
        pushButton_hanzi_4->setFont(font1);
        pushButton_hanzi_2 = new QPushButton(IMEall);
        pushButton_hanzi_2->setObjectName(QString::fromUtf8("pushButton_hanzi_2"));
        pushButton_hanzi_2->setGeometry(QRect(140, 50, 45, 35));
        pushButton_hanzi_2->setFont(font1);
        pushButton_hanzi_3 = new QPushButton(IMEall);
        pushButton_hanzi_3->setObjectName(QString::fromUtf8("pushButton_hanzi_3"));
        pushButton_hanzi_3->setGeometry(QRect(190, 50, 45, 35));
        pushButton_hanzi_3->setFont(font1);
        pushButton_hanzi_left = new QPushButton(IMEall);
        pushButton_hanzi_left->setObjectName(QString::fromUtf8("pushButton_hanzi_left"));
        pushButton_hanzi_left->setGeometry(QRect(40, 50, 41, 35));
        pushButton_hanzi_left->setFont(font);
        pushButton_hanzi_right = new QPushButton(IMEall);
        pushButton_hanzi_right->setObjectName(QString::fromUtf8("pushButton_hanzi_right"));
        pushButton_hanzi_right->setGeometry(QRect(490, 50, 51, 35));
        pushButton_hanzi_right->setFont(font);
        pushButton_hanzi_1 = new QPushButton(IMEall);
        pushButton_hanzi_1->setObjectName(QString::fromUtf8("pushButton_hanzi_1"));
        pushButton_hanzi_1->setGeometry(QRect(90, 50, 45, 35));
        pushButton_hanzi_1->setFont(font1);
        lineEdit_pinyin = new QLineEdit(IMEall);
        lineEdit_pinyin->setObjectName(QString::fromUtf8("lineEdit_pinyin"));
        lineEdit_pinyin->setGeometry(QRect(6, 10, 661, 35));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font3.setPointSize(21);
        font3.setBold(true);
        font3.setWeight(75);
        lineEdit_pinyin->setFont(font3);
        lineEdit_pinyin->setFrame(false);
        pushButton_n3 = new QPushButton(IMEall);
        pushButton_n3->setObjectName(QString::fromUtf8("pushButton_n3"));
        pushButton_n3->setGeometry(QRect(140, 90, 45, 45));
        pushButton_n3->setFont(font);
        pushButton_backspace = new QPushButton(IMEall);
        pushButton_backspace->setObjectName(QString::fromUtf8("pushButton_backspace"));
        pushButton_backspace->setGeometry(QRect(450, 240, 41, 45));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        pushButton_backspace->setFont(font4);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/ime/icon4ime/bs_s.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon3.addFile(QString::fromUtf8(":/ime/icon4ime/bs_s.png"), QSize(), QIcon::Normal, QIcon::On);
        pushButton_backspace->setIcon(icon3);
        pushButton_backspace->setIconSize(QSize(48, 48));
        pushButton_n0 = new QPushButton(IMEall);
        pushButton_n0->setObjectName(QString::fromUtf8("pushButton_n0"));
        pushButton_n0->setGeometry(QRect(490, 90, 45, 45));
        pushButton_n0->setFont(font);
        pushButton_n1 = new QPushButton(IMEall);
        pushButton_n1->setObjectName(QString::fromUtf8("pushButton_n1"));
        pushButton_n1->setGeometry(QRect(40, 90, 45, 45));
        pushButton_n1->setFont(font);
        pushButton_n1->setFocusPolicy(Qt::ClickFocus);
        pushButton_n6 = new QPushButton(IMEall);
        pushButton_n6->setObjectName(QString::fromUtf8("pushButton_n6"));
        pushButton_n6->setGeometry(QRect(290, 90, 45, 45));
        pushButton_n6->setFont(font);
        pushButton_deng = new QPushButton(IMEall);
        pushButton_deng->setObjectName(QString::fromUtf8("pushButton_deng"));
        pushButton_deng->setGeometry(QRect(50, 290, 45, 45));
        pushButton_deng->setFont(font);
        pushButton_gang = new QPushButton(IMEall);
        pushButton_gang->setObjectName(QString::fromUtf8("pushButton_gang"));
        pushButton_gang->setGeometry(QRect(100, 290, 45, 45));
        pushButton_gang->setFont(font);
        pushButton_n5 = new QPushButton(IMEall);
        pushButton_n5->setObjectName(QString::fromUtf8("pushButton_n5"));
        pushButton_n5->setGeometry(QRect(240, 90, 45, 45));
        pushButton_n5->setFont(font);
        pushButton_n7 = new QPushButton(IMEall);
        pushButton_n7->setObjectName(QString::fromUtf8("pushButton_n7"));
        pushButton_n7->setGeometry(QRect(340, 90, 45, 45));
        pushButton_n7->setFont(font);
        pushButton_n8 = new QPushButton(IMEall);
        pushButton_n8->setObjectName(QString::fromUtf8("pushButton_n8"));
        pushButton_n8->setGeometry(QRect(390, 90, 45, 45));
        pushButton_n8->setFont(font);
        pushButton_n4 = new QPushButton(IMEall);
        pushButton_n4->setObjectName(QString::fromUtf8("pushButton_n4"));
        pushButton_n4->setGeometry(QRect(190, 90, 45, 45));
        pushButton_n4->setFont(font);
        pushButton_n9 = new QPushButton(IMEall);
        pushButton_n9->setObjectName(QString::fromUtf8("pushButton_n9"));
        pushButton_n9->setGeometry(QRect(440, 90, 45, 45));
        pushButton_n9->setFont(font);
        QWidget::setTabOrder(pushButton_hanzi_left, pushButton_hanzi_1);
        QWidget::setTabOrder(pushButton_hanzi_1, pushButton_hanzi_2);
        QWidget::setTabOrder(pushButton_hanzi_2, pushButton_hanzi_3);
        QWidget::setTabOrder(pushButton_hanzi_3, pushButton_hanzi_4);
        QWidget::setTabOrder(pushButton_hanzi_4, pushButton_hanzi_5);
        QWidget::setTabOrder(pushButton_hanzi_5, pushButton_hanzi_6);
        QWidget::setTabOrder(pushButton_hanzi_6, pushButton_hanzi_7);
        QWidget::setTabOrder(pushButton_hanzi_7, pushButton_hanzi_8);
        QWidget::setTabOrder(pushButton_hanzi_8, pushButton_hanzi_right);
        QWidget::setTabOrder(pushButton_hanzi_right, pushButton_n1);
        QWidget::setTabOrder(pushButton_n1, pushButton_n2);
        QWidget::setTabOrder(pushButton_n2, pushButton_n3);
        QWidget::setTabOrder(pushButton_n3, pushButton_n4);
        QWidget::setTabOrder(pushButton_n4, pushButton_n5);
        QWidget::setTabOrder(pushButton_n5, pushButton_n6);
        QWidget::setTabOrder(pushButton_n6, pushButton_n7);
        QWidget::setTabOrder(pushButton_n7, pushButton_n8);
        QWidget::setTabOrder(pushButton_n8, pushButton_n9);
        QWidget::setTabOrder(pushButton_n9, pushButton_n0);
        QWidget::setTabOrder(pushButton_n0, pushButton_gang);
        QWidget::setTabOrder(pushButton_gang, pushButton_deng);
        QWidget::setTabOrder(pushButton_deng, pushButton_backspace);
        QWidget::setTabOrder(pushButton_backspace, pushButton_q);
        QWidget::setTabOrder(pushButton_q, pushButton_w);
        QWidget::setTabOrder(pushButton_w, pushButton_e);
        QWidget::setTabOrder(pushButton_e, pushButton_r);
        QWidget::setTabOrder(pushButton_r, pushButton_t);
        QWidget::setTabOrder(pushButton_t, pushButton_y);
        QWidget::setTabOrder(pushButton_y, pushButton_u);
        QWidget::setTabOrder(pushButton_u, pushButton_i);
        QWidget::setTabOrder(pushButton_i, pushButton_o);
        QWidget::setTabOrder(pushButton_o, pushButton_p);
        QWidget::setTabOrder(pushButton_p, pushButton_zuokuo);
        QWidget::setTabOrder(pushButton_zuokuo, pushButton_youkuo);
        QWidget::setTabOrder(pushButton_youkuo, pushButton_backsplash);
        QWidget::setTabOrder(pushButton_backsplash, pushButton_a);
        QWidget::setTabOrder(pushButton_a, pushButton_s);
        QWidget::setTabOrder(pushButton_s, pushButton_d);
        QWidget::setTabOrder(pushButton_d, pushButton_f);
        QWidget::setTabOrder(pushButton_f, pushButton_g);
        QWidget::setTabOrder(pushButton_g, pushButton_h);
        QWidget::setTabOrder(pushButton_h, pushButton_j);
        QWidget::setTabOrder(pushButton_j, pushButton_k);
        QWidget::setTabOrder(pushButton_k, pushButton_l);
        QWidget::setTabOrder(pushButton_l, pushButton_semicolon);
        QWidget::setTabOrder(pushButton_semicolon, pushButton_quote);
        QWidget::setTabOrder(pushButton_quote, pushButton_enter);
        QWidget::setTabOrder(pushButton_enter, pushButton_z);
        QWidget::setTabOrder(pushButton_z, pushButton_x);
        QWidget::setTabOrder(pushButton_x, pushButton_c);
        QWidget::setTabOrder(pushButton_c, pushButton_v);
        QWidget::setTabOrder(pushButton_v, pushButton_b);
        QWidget::setTabOrder(pushButton_b, pushButton_n);
        QWidget::setTabOrder(pushButton_n, pushButton_m);
        QWidget::setTabOrder(pushButton_m, pushButton_comma);
        QWidget::setTabOrder(pushButton_comma, pushButton_period);
        QWidget::setTabOrder(pushButton_period, pushButton_splash);
        QWidget::setTabOrder(pushButton_splash, pushButton_shift);
        QWidget::setTabOrder(pushButton_shift, pushButton_whitespace);
        QWidget::setTabOrder(pushButton_whitespace, pushButton_is_hanzi);
        QWidget::setTabOrder(pushButton_is_hanzi, pushButton_ok);
        QWidget::setTabOrder(pushButton_ok, pushButton_left);
        QWidget::setTabOrder(pushButton_left, pushButton_down);
        QWidget::setTabOrder(pushButton_down, pushButton_right);
        QWidget::setTabOrder(pushButton_right, pushButton_up);
        QWidget::setTabOrder(pushButton_up, lineEdit_pinyin);

        retranslateUi(IMEall);

        QMetaObject::connectSlotsByName(IMEall);
    } // setupUi

    void retranslateUi(QDialog *IMEall)
    {
        IMEall->setWindowTitle(QApplication::translate("IMEall", "Dialog", 0, QApplication::UnicodeUTF8));
        pushButton_u->setText(QApplication::translate("IMEall", "u", 0, QApplication::UnicodeUTF8));
        pushButton_t->setText(QApplication::translate("IMEall", "t", 0, QApplication::UnicodeUTF8));
        pushButton_y->setText(QApplication::translate("IMEall", "y", 0, QApplication::UnicodeUTF8));
        pushButton_i->setText(QApplication::translate("IMEall", "i", 0, QApplication::UnicodeUTF8));
        pushButton_q->setText(QApplication::translate("IMEall", "q", 0, QApplication::UnicodeUTF8));
        pushButton_zuokuo->setText(QApplication::translate("IMEall", "[", 0, QApplication::UnicodeUTF8));
        pushButton_p->setText(QApplication::translate("IMEall", "p", 0, QApplication::UnicodeUTF8));
        pushButton_r->setText(QApplication::translate("IMEall", "r", 0, QApplication::UnicodeUTF8));
        pushButton_youkuo->setText(QApplication::translate("IMEall", "]", 0, QApplication::UnicodeUTF8));
        pushButton_w->setText(QApplication::translate("IMEall", "w", 0, QApplication::UnicodeUTF8));
        pushButton_o->setText(QApplication::translate("IMEall", "o", 0, QApplication::UnicodeUTF8));
        pushButton_e->setText(QApplication::translate("IMEall", "e", 0, QApplication::UnicodeUTF8));
        pushButton_j->setText(QApplication::translate("IMEall", "j", 0, QApplication::UnicodeUTF8));
        pushButton_g->setText(QApplication::translate("IMEall", "g", 0, QApplication::UnicodeUTF8));
        pushButton_h->setText(QApplication::translate("IMEall", "h", 0, QApplication::UnicodeUTF8));
        pushButton_k->setText(QApplication::translate("IMEall", "k", 0, QApplication::UnicodeUTF8));
        pushButton_a->setText(QApplication::translate("IMEall", "a", 0, QApplication::UnicodeUTF8));
        pushButton_quote->setText(QApplication::translate("IMEall", "'", 0, QApplication::UnicodeUTF8));
        pushButton_semicolon->setText(QApplication::translate("IMEall", ";", 0, QApplication::UnicodeUTF8));
        pushButton_f->setText(QApplication::translate("IMEall", "f", 0, QApplication::UnicodeUTF8));
        pushButton_enter->setText(QString());
        pushButton_s->setText(QApplication::translate("IMEall", "s", 0, QApplication::UnicodeUTF8));
        pushButton_l->setText(QApplication::translate("IMEall", "l", 0, QApplication::UnicodeUTF8));
        pushButton_d->setText(QApplication::translate("IMEall", "d", 0, QApplication::UnicodeUTF8));
        pushButton_m->setText(QApplication::translate("IMEall", "m", 0, QApplication::UnicodeUTF8));
        pushButton_b->setText(QApplication::translate("IMEall", "b", 0, QApplication::UnicodeUTF8));
        pushButton_n->setText(QApplication::translate("IMEall", "n", 0, QApplication::UnicodeUTF8));
        pushButton_comma->setText(QApplication::translate("IMEall", ",", 0, QApplication::UnicodeUTF8));
        pushButton_z->setText(QApplication::translate("IMEall", "z", 0, QApplication::UnicodeUTF8));
        pushButton_splash->setText(QApplication::translate("IMEall", "/", 0, QApplication::UnicodeUTF8));
        pushButton_v->setText(QApplication::translate("IMEall", "v", 0, QApplication::UnicodeUTF8));
        pushButton_x->setText(QApplication::translate("IMEall", "x", 0, QApplication::UnicodeUTF8));
        pushButton_period->setText(QApplication::translate("IMEall", ".", 0, QApplication::UnicodeUTF8));
        pushButton_c->setText(QApplication::translate("IMEall", "c", 0, QApplication::UnicodeUTF8));
        pushButton_shift->setText(QString());
        pushButton_whitespace->setText(QString());
        pushButton_up->setText(QApplication::translate("IMEall", "\342\206\221", 0, QApplication::UnicodeUTF8));
        pushButton_backsplash->setText(QApplication::translate("IMEall", "\\", 0, QApplication::UnicodeUTF8));
        pushButton_left->setText(QApplication::translate("IMEall", "\342\206\220", 0, QApplication::UnicodeUTF8));
        pushButton_right->setText(QApplication::translate("IMEall", "\342\206\222", 0, QApplication::UnicodeUTF8));
        pushButton_down->setText(QApplication::translate("IMEall", "\342\206\223", 0, QApplication::UnicodeUTF8));
        pushButton_n2->setText(QApplication::translate("IMEall", "2", 0, QApplication::UnicodeUTF8));
        pushButton_is_hanzi->setText(QString());
        pushButton_ok->setText(QApplication::translate("IMEall", "\342\210\232", 0, QApplication::UnicodeUTF8));
        pushButton_hanzi_7->setText(QString());
        pushButton_hanzi_5->setText(QString());
        pushButton_hanzi_6->setText(QString());
        pushButton_hanzi_8->setText(QString());
        pushButton_hanzi_4->setText(QString());
        pushButton_hanzi_2->setText(QString());
        pushButton_hanzi_3->setText(QString());
        pushButton_hanzi_left->setText(QApplication::translate("IMEall", "\342\206\220", 0, QApplication::UnicodeUTF8));
        pushButton_hanzi_right->setText(QApplication::translate("IMEall", "\342\206\222", 0, QApplication::UnicodeUTF8));
        pushButton_hanzi_1->setText(QString());
        lineEdit_pinyin->setText(QString());
        pushButton_n3->setText(QApplication::translate("IMEall", "3", 0, QApplication::UnicodeUTF8));
        pushButton_backspace->setText(QString());
        pushButton_n0->setText(QApplication::translate("IMEall", "0", 0, QApplication::UnicodeUTF8));
        pushButton_n1->setText(QApplication::translate("IMEall", "1", 0, QApplication::UnicodeUTF8));
        pushButton_n6->setText(QApplication::translate("IMEall", "6", 0, QApplication::UnicodeUTF8));
        pushButton_deng->setText(QApplication::translate("IMEall", "=", 0, QApplication::UnicodeUTF8));
        pushButton_gang->setText(QApplication::translate("IMEall", "-", 0, QApplication::UnicodeUTF8));
        pushButton_n5->setText(QApplication::translate("IMEall", "5", 0, QApplication::UnicodeUTF8));
        pushButton_n7->setText(QApplication::translate("IMEall", "7", 0, QApplication::UnicodeUTF8));
        pushButton_n8->setText(QApplication::translate("IMEall", "8", 0, QApplication::UnicodeUTF8));
        pushButton_n4->setText(QApplication::translate("IMEall", "4", 0, QApplication::UnicodeUTF8));
        pushButton_n9->setText(QApplication::translate("IMEall", "9", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class IMEall: public Ui_IMEall {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SYSZUXPINYIN_H
